apiVersion: v2
name: malcolm
description: A Helm chart for Deploying Malcolm in Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. It should match appVersion, with the addition
# of a packaging revision, beginning at -0 and incrementing if there are
# multiple revisions of the chart for a single Malcolm release
# (e.g., 25.09.0-0, 25.09.0-1, etc.).
version: 25.09.0-0

# This is the version number of the application being deployed. The application
# version tracks the Malcolm release number (https://github.com/idaholab/Malcolm/releases),
# which follows calendar versioning (https://calver.org/), e.g., 25.09.0.
# This variable is also used to determine the tag of the Malcolm container
# images pulled (unless overridden in values.yaml).
appVersion: "25.09.0"
