{{- $claims := ternary .Values.storage.production.claims .Values.storage.development.claims .Values.is_production }}
{{- range $key, $claim := $claims }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $claim.name }}-claim
spec:
  storageClassName: {{ $claim.className }}
  accessModes:
    - {{ default .Values.storage.defaultAccessMode $claim.accessMode }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ $claim.size }}

{{- end }}
