{{- $global_storage_class_name := .Values.storage_class_name -}}

{{- if .Values.is_production }}
  {{- with .Values.storage.production }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pcap-claim
spec:
  storageClassName: {{ default $global_storage_class_name .pcap_claim.classNameOverride }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .pcap_claim.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zeek-claim
spec:
  storageClassName: {{ default $global_storage_class_name .zeek_claim.classNameOverride }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .zeek_claim.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suricata-claim-offline
spec:
  storageClassName: {{ default $global_storage_class_name .suricata_claim.classNameOverride }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .suricata_claim.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-claim
spec:
  storageClassName: {{ default $global_storage_class_name .config_claim.classNameOverride }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .config_claim.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runtime-logs-claim
spec:
  storageClassName: {{ default $global_storage_class_name .runtime_logs_claim.classNameOverride }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .runtime_logs_claim.size }}

  {{- end }}
{{- else }}
  {{- with .Values.storage.development }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pcap-claim
spec:
  storageClassName: {{ default $global_storage_class_name .pcap_claim.classNameOverride }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .pcap_claim.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zeek-claim
spec:
  storageClassName: {{ default $global_storage_class_name .zeek_claim.classNameOverride }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .zeek_claim.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suricata-claim-offline
spec:
  storageClassName: {{ default $global_storage_class_name .suricata_claim.classNameOverride }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .suricata_claim.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-claim
spec:
  storageClassName: {{ default $global_storage_class_name .config_claim.classNameOverride }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .config_claim.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runtime-logs-claim
spec:
  storageClassName: {{ default $global_storage_class_name .runtime_logs_claim.classNameOverride }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .runtime_logs_claim.size }}

  {{- end }}
{{- end }}
